---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15

inputs:
  - name: gremgo-neptune
    path: gremgo-neptune

run:
  path: gremgo-neptune/ci/scripts/build.sh
